# -*- coding: utf-8 -*-
"""LVDASUSR130_Q3_srilekha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNVqVDzXzNMQItnVmzHLas6zm4oXreIy
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
d= pd.read_csv('seeds.csv')
d.head()

d.shape
d.info()
d.isnull().sum()

d=d.dropna()
d.isnull().sum()

for c in d.columns:
    if d[c].dtype == 'object' and '?' in d[c].unique():
        d = d[d[c] != '?']
    d[c] = pd.to_numeric(d[c], errors='coerce')

d.dropna(inplace=True)

plt.figure(figsize=(11, 7))
for i, c in enumerate(d.columns, 1):
    plt.subplot(3, 3, i)
    sns.histplot(d[c], kde=True)
    plt.title(c)
plt.tight_layout()
plt.show()