# -*- coding: utf-8 -*-
"""LVDASUSR130_Q4_srilekha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bHHVdJ7uSmDlgh336rjBxi6LuUuK9ZFm
"""

#4
import pandas as pd
from sklearn.ensemble import IsolationForest
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
data = pd.read_csv("social_network.csv")
features = ["login_activity", "posting_activity", "social_connections"]
x = data[features]
typee = IsolationForest()
typee.fit(x)
y_pred = typee.predict(x)
data["a_score"] = typee.decision_function(x)
anomaly= data.loc[data["a_score"] < 0]
data_test= pd.read_csv("social_network.csv")
y=data_test[["login_activity", "posting_activity", "social_connections"]]
data_values=y.values
f=data_values
r=[]
for i in f:
  m=typee.predict([i])
  if m==[1]:
    r.append('Not Anomaly')
  elif m==[-1]:
    r.append('Anomaly')
data_test['Anomaly']=r
print(data_test)
plt.scatter(data["social_connections"], data["a_score"], label="Not Anomaly")
plt.scatter(anomaly["social_connections"], anomaly["a_score"], color="g", label="Anomaly")
plt.xlabel("Social Connections")
plt.ylabel("a_score")
plt.legend()
plt.show()
data_test.head()