# -*- coding: utf-8 -*-
"""LVADSUSR130_srilekha_lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_S87gQfvVUPJymIvXj6Iy6oBcKby63th
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('expenses.csv')

df.head()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['smoker']=le.fit_transform(df['smoker'])
df['sex']=le.fit_transform(df['sex'])
df['region']=le.fit_transform(df['region'])

df.head()

df.corr()

sns.heatmap(df.corr(),annot=True)

df=df.drop('sex',axis='columns')
df=df.drop('children',axis='columns')
df=df.drop('region',axis='columns')

df.head()

y=df.iloc[:,3]
x=df.iloc[:,:-1]
print(x)

df.isnull().sum()

df.duplicated().sum()

sns.boxplot(df['charges'])

sns.regplot(x=df['charges'],y=df['age'])

sns.regplot(x=df['charges'],y=df['bmi'])

sns.regplot(x=df['charges'],y=df['smoker'])

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.3,random_state=555)
lr.fit(train_x,train_y)
pred=lr.predict(test_x)
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(test_y, pred)
print(mse)
r2 = r2_score(test_y,pred)
print(r2)

from scipy import stats
z_scores = stats.zscore(df)
abs_z_scores = np.abs(z_scores)
filtered_entries = (abs_z_scores < 3).all(axis=1)
df_cleaned = df[filtered_entries]
print("Actual DataFrame:")
print(df.shape)
print("\nData after removing outliers:")